import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { SellerProvider } from "@/context/SellerContext";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SellerProvider>
      <body
        className={`${geistSans.variable} ${poppins.variable} ${geistMono.variable} antialiased dark:bg-black`}>
          <ThemeProvider attribute="data-theme" defaultTheme="light" enableSystem={false}>
        {children}
        </ThemeProvider>
      </body>
      </SellerProvider>
    </html>
  );
}
